### ISSUE TITLE
The `1st entry of padding` argument must be a tuple of 2 integers. Received: 3

### ISSUE THREAD

**Issue by mrlzla** [qxcv/caffe2keras#5]
python -m caffe2keras deploy_google_64.prototxt trained_google_64_v01_iter_8000.caffemodel keras-output-model.h5
Using Theano backend.
Converting model...
CREATING MODEL
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vladik/ml/caffe2keras/caffe2keras/__main__.py", line 32, in <module>
    main()
  File "/home/vladik/ml/caffe2keras/caffe2keras/__main__.py", line 22, in main
    model = convert.caffe_to_keras(args.prototxt, args.caffemodel, args.debug)
  File "caffe2keras/convert.py", line 358, in caffe_to_keras
    tuple(config.input_dim[1:]))
  File "caffe2keras/convert.py", line 471, in create_model
    out_blobs = converter(layer, layer_bottom_blobs)
  File "caffe2keras/convert.py", line 53, in wrapper
    rv = converter_func(spec, bot_arg)
  File "caffe2keras/convert.py", line 118, in handle_conv
    data_format='channels_first')(bottom)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 1306, in __init__
    '1st entry of padding')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/conv_utils.py", line 30, in normalize_tuple
    str(n) + ' integers. Received: ' + str(value))
ValueError: The `1st entry of padding` argument must be a tuple of 2 integers. Received: 3

**Comment by qxcv** [comment]
Hmm, looks like a similar problem to #2 (although this time it's actually the code in this repo…). Converting the `width` and `height` in `handle_conv` to `int`s should fix the problem for good, but in the mean time, running on Python 3 should make it work.
